### PR TITLE
Horizontal version

### PR DESCRIPTION
**Pull request by kostin1221**
For horizontal menus need simply add flag "vertical: false" to options object

### CODE REVIEW

**Comment by kostin1221** [comment]
This menu on http://www.mebelion.ru

**Comment by DavidBadura** [comment]
+1

**Comment by jbate** [comment]
This would be a valuable addition to the repo.

**Comment by cabhishek** [comment]
+1

**Comment by tchapi** [comment]
+1

**Comment by kamens** [comment]
Check out the "submenuDirection" option provided by https://github.com/kamens/jQuery-menu-aim/commit/5e321a8a6905ba93697d91d84458b331986b0ee6

Choosing a value of "above" or "below" lets menu-aim support horizontal menus. Lemme know how it goes.

**Comment by jonnymaceachern** [comment]
@kamens Do you have a horizontal example that uses the below/above option (similar to the one linked above)?

**Comment by banesto** [comment]
@jonnymaceachern, you can try [this](https://rawgit.com/banesto/jQuery-menu-aim/master/advanced_example/index.html)

**Pull request closed without merging**
